# Entorno LEMP Basico 
version: '3.8'
services:
  # Contenedor de aplicacion php (Solo interpreta el lenguaje)
  # Ip flotante 192.168.20.4
  php1:
    container_name: SERVER_PHP_1
    build:
      context: ./php
    volumes:
      - ./app:/srv/www/app
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file: ./.env
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.2
  php2:
    container_name: SERVER_PHP_2
    build:
      context: ./php
    volumes:
      - ./app:/srv/www/app
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file: ./.env
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.3
  # Contenedor Base de Datos SQL
  db:
    container_name: DB_SQL
    image: mariadb:latest
    hostname: basedatos.local
    volumes: 
        - ./mariadb/db:/var/lib/mysql 
    env_file: ./.env
    restart: unless-stopped
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.5
  # Contenedor Base de Datos REDIS Cache MYSQL   
  redis:
    container_name: REDIS_CACHE_MYSQL
    image: redis:latest
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis/mysql:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.6
  # Contenedor Base de Datos REDIS Control sesiones PHP
  #  Ip Flotante 192.168.20.9
  redis1:
    container_name: REDIS_CACHE_SESIONES_1
    image: redis:latest
    volumes:
      - ./redis/sessions:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.7
  redis2:
    container_name: REDIS_CACHE_SESIONES_2
    image: redis:latest
    volumes:
      - ./redis/sessions:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.8
  # Contenedor Base de Datos Mongo    
  mongo:
    container_name: DB_MONGO
    image: mongo:latest
    volumes:
      - ./mongo:/data
    env_file: ./.env
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.10
#### <<< Multiples Server Web con Balanceo de cargas -- Haproxy y VRRP>>>>>>>        
# Contenedores Haproxy  IP FLOTANTE 192.168.20.13
  haproxy1: 
    container_name: BALANCEADOR_1
    hostname: haproxy.local
    build: 
      context: ./haproxy
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.11

  haproxy2: 
    container_name: BALANCEADOR_2
    hostname: haproxy.local
    build: 
      context: ./haproxy
    privileged: true
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 2080:80
      - 2043:443
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.12
  # Contenedores Server Web
  nginx1: 
    container_name: NGINX_1
    build: 
      context: ./nginx
    hostname: wiediilocal.co
    volumes:
      - ./app:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.14

  nginx2: 
    container_name: NGINX_2
    build: 
      context: ./nginx
    hostname: wiediilocal.co
    volumes:
      - ./app:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.15

  nginx3: 
    container_name: NGINX_3
    build: 
      context: ./nginx
    hostname: wiediilocal.co
    volumes:
      - ./app:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.16

  # # Gestor visual de Base de Datos SOLO POR EL CURSO
  phpmyadmin:
    container_name: GESTOR_BASE_DATOS
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin.local
    ports:
      - 8080:80
    depends_on: 
      - db
    volumes: 
        - ./php/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - ./php/phpmyadmin/sessions/:/sessions/
    env_file: ./.env
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.50
networks:
  infra_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1