# Entorno LEMP Basico 
version: '3.8'
services:
  # Contenedor de aplicacion php
  php:
    container_name: SERVER_APP
    build:
      context: ./server/php
    volumes:
      - ./page:/srv/www/api
      - ./server/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./server/php/ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
      - net
  # Contenedor Base de Datos SQL
  db:
    container_name: BASE_DATOS
    image: mariadb:latest
    hostname: basedatos.local
    depends_on: 
      - php
    volumes: 
        - ./server/mariadb/db:/var/lib/mysql 
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net
  # Contenedor Base de Datos REDIS    
  redis:
    container_name: CACHE_REDIS
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks: 
        - net 
  # Gestor visual de Base de Datos SOLO POR EL CURSO
  phpmyadmin:
    container_name: GESTOR_BASE_DATOS
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin.local
    ports:
      - 8080:80
    depends_on: 
      - db
    volumes: 
        - ./server/php/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - ./server/php/phpmyadmin/sessions/:/sessions/
    env_file: ./server/.env
    restart: unless-stopped
    networks: 
        - net 
  # Servidor Web
  nginx1: 
    container_name: NGINX_1
    image: nginx:alpine
    hostname: web.local
    ports: 
      - 80:80
    volumes:
      - ./page:/srv/www/api
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      - net
  # Servidor SFTP
  archivos: 
    container_name: SERVER_SFTP
    build:
      context: ./server/storage
    hostname: sftp.local
    ports: 
      - "2222:22"
    volumes:
      - ./server/storage/shared:/home/foo/upload
    command: posesco:Y%ADL4*h!MWhsjS:1001
    restart: unless-stopped
    networks: 
        - net 
networks:
  net: