# Entorno LEMP Basico 
version: '3.8'
services:
  # Contenedor de aplicacion php (Solo interpreta el lenguaje)
  php:
    container_name: SERVER_APP
    build:
      context: ./php
    volumes:
      - ./page:/srv/www/app
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file: ./.env
    restart: unless-stopped
    networks: 
      infra_lab:
        ipv4_address: 192.168.0.2
  # Contenedor Base de Datos SQL
  db:
    container_name: DB_SQL
    image: mariadb:latest
    hostname: basedatos.local
    depends_on: 
      - php
    volumes: 
        - ./mariadb/db:/var/lib/mysql 
    env_file: ./.env
    restart: unless-stopped
    networks: 
      infra_lab:
        ipv4_address: 192.168.0.3
  # Contenedor Base de Datos REDIS    
  redis:
    container_name: DB_REDIS
    image: redis:latest
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.4
  # Contenedor Base de Datos Mongo    
  mongo:
    container_name: DB_MONGO
    image: mongo:latest
    # ports:
    #   - "6379:6379"
    volumes:
      - ./mongo:/data
    env_file: ./.env
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.5
#### <<< Multiples Server Web con Balanceo de cargas -- Haproxy >>>>>>>        
# Contenedores Haproxy  IP FLOTANTE 192.168.0.6
  haproxy1: 
    container_name: BALANCEADOR_1
    hostname: haproxy.local
    build: 
      context: ./haproxy
    ports:
      - 80:80
      - 8989:8989
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
    # restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.7
  # haproxy2: 
    # container_name: BALANCEADOR_2
    # hostname: haproxy.local
    # build: 
    #   context: ./haproxy
    # ports:
    #   - 80:80
    # depends_on: 
    #   - nginx1
    #   - nginx2
    #   - nginx3
    # # restart: unless-stopped
    # networks:
    #   infra_lab:
    #     ipv4_address: 192.168.0.8
  # Contenedores Server Web
  nginx1: 
    container_name: NGINX_1
    image: nginx:alpine
    hostname: web.local
    volumes:
      - ./page:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.9
  nginx2: 
    container_name: NGINX_2
    image: nginx:alpine
    hostname: web.local
    volumes:
      - ./page:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.10
  nginx3: 
    container_name: NGINX_3
    image: nginx:alpine
    hostname: web.local
    volumes:
      - ./page:/srv/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.0.11
  # # Servidor SFTP
  # archivos: 
  #   container_name: SERVER_SFTP
  #   build:
  #     context: ./storage
  #   hostname: sftp.local
  #   # ports: 
  #   #   - "2222:22"
  #   volumes:
  #     - ./storage/shared:/home/foo/upload
  #   command: posesco:Y%ADL4*h!MWhsjS:1001
  #   restart: unless-stopped
  #   networks: 
  #       - infra_lab
  # # Gestor visual de Base de Datos SOLO POR EL CURSO
  # phpmyadmin:
  #   container_name: GESTOR_BASE_DATOS
  #   image: phpmyadmin/phpmyadmin:latest
  #   hostname: phpmyadmin.local
  #   ports:
  #     - 8080:80
  #   depends_on: 
  #     - db
  #   volumes: 
  #       - ./php/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  #       - ./php/phpmyadmin/sessions/:/sessions/
  #   env_file: ./.env
  #   restart: unless-stopped
  #   networks: 
  #       - infra_lab 
networks:
  infra_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1