# Entorno LEMP Basico 
version: '3.8'
services:
   # Contenedor de aplicacion php (Solo interpreta el lenguaje)
   # Ip flotante 192.168.20.4
  php1:
    container_name: SERVER_PHP_1
    hostname: php1.local
    build:
      context: ./php
    volumes:
      - ./app:/var/www/app
      - ./php/key:/root/.ssh
      - ./php/conf/sshd_config:/etc/ssh/sshd_config
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf/keepalived_server_a.conf:/etc/keepalived/keepalived.conf
    env_file: ./.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.2

  php2:
    container_name: SERVER_PHP_2
    hostname: php2.local
    build:
      context: ./php
    volumes:
      - ./app:/var/www/app
      - ./php/key/authorized_keys:/root/.ssh/authorized_keys
      - ./php/conf/sshd_config:/etc/ssh/sshd_config
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf/keepalived_server_b.conf:/etc/keepalived/keepalived.conf
    env_file: ./.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.3
  # Contenedor Base de Datos SQL
  db:
    container_name: DB_SQL
    image: mariadb:10
    hostname: basedatos.local
    volumes: 
        - ./mariadb/db:/var/lib/mysql 
    env_file: ./.env
    restart: unless-stopped
    networks: 
      infra_lab:
        ipv4_address: 192.168.20.5
  # Contenedor Base de Datos REDIS Cache MYSQL   
  redis:
    container_name: REDIS_CACHE_MYSQL
    hostname: cachemysql.local
    image: redis:6
    volumes:
      - ./redis_cache:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.6
  # Contenedor Base de Datos REDIS Control sesiones PHP
  #  Ip Flotante 192.168.20.9
  redis1:
    container_name: REDIS_CACHE_SESIONES_1
    hostname: sesiones1.local
    build: 
      context: ./redis_sesiones
    volumes:
      - ./redis_sesiones/data:/data
      - ./redis_sesiones/key:/root/.ssh
      - ./redis_sesiones/conf/sshd_config:/etc/ssh/sshd_config
      - ./redis_sesiones/conf/keepalived_server_a.conf:/etc/keepalived/keepalived.conf
    command: redis-server --appendonly yes
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.7

  redis2:
    container_name: REDIS_CACHE_SESIONES_2
    hostname: sesiones2.local
    build: 
      context: ./redis_sesiones
    volumes:
      - ./redis_sesiones/data:/data
      - ./redis_sesiones/key/authorized_keys:/root/.ssh/authorized_keys
      - ./redis_sesiones/conf/sshd_config:/etc/ssh/sshd_config
      - ./redis_sesiones/conf/keepalived_server_b.conf:/etc/keepalived/keepalived.conf
    command: redis-server --appendonly yes
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.8
  # Contenedor Base de Datos Mongo    
  mongo:
    container_name: DB_MONGO
    hostname: mongo.local
    image: mongo:4
    volumes:
      - ./mongo/conf:/etc/mongo
      - ./mongo/data:/data
    env_file: ./.env
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.10
# <<< Multiples Server Web con Balanceo de cargas -- Haproxy y VRRP>>>>>>>        
# Contenedores Haproxy  IP FLOTANTE 192.168.20.13
  haproxy1: 
    container_name: BALANCEADOR_1
    hostname: haproxy1.local
    build: 
      context: ./haproxy
    volumes:
      - ./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/key:/root/.ssh
      - ./haproxy/conf/sshd_config:/etc/ssh/sshd_config
      - ./haproxy/conf/keepalived/keepalived_server_a.conf:/etc/keepalived/keepalived.conf      
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.11

  haproxy2: 
    container_name: BALANCEADOR_2
    hostname: haproxy2.local
    build: 
      context: ./haproxy
    volumes:
      - ./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/key/authorized_keys:/root/.ssh/authorized_keys
      - ./haproxy/conf/sshd_config:/etc/ssh/sshd_config
      - ./haproxy/conf/keepalived/keepalived_server_b.conf:/etc/keepalived/keepalived.conf      
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 2080:80
      - 2443:443
    depends_on: 
      - nginx1
      - nginx2
      - nginx3
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.12
  # Contenedores Server Web
  nginx1: 
    container_name: NGINX_1
    hostname: web1.local
    image: nginx:1.19
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.14

  nginx2: 
    container_name: NGINX_2
    hostname: web2.local
    image: nginx:1.19
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.15

  nginx3: 
    container_name: NGINX_3
    hostname: web3.local
    image: nginx:1.19
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      infra_lab:
        ipv4_address: 192.168.20.16
# Contenedores SFTP ip Flotante <<<<<< 192.168.20.19 >>>>>>>
  ssh_files1:
    container_name: ALMACEN_FILES_1
    hostname: almacen1.local
    build:
      context: ./ssh_files
    volumes:
      - ./ssh_files/key:/root/.ssh
      - ./ssh_files/conf/sshd_config:/etc/ssh/sshd_config
      - ./ssh_files/conf/lsyncd.conf.lua:/etc/lsyncd/lsyncd.conf.lua
      - ./ssh_files/storage_a:/home/remote_user/almacen
      - ./ssh_files/conf/keepalived_server_a.conf:/etc/keepalived/keepalived.conf
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.17

  ssh_files2:
    container_name: ALMACEN_FILES_2
    hostname: almacen2.local
    build:
      context: ./ssh_files
    volumes:
      - ./ssh_files/conf/sshd_config:/etc/ssh/sshd_config
      - ./ssh_files/storage_b:/home/remote_user/almacen
      - ./ssh_files/key/authorized_keys:/root/.ssh/authorized_keys
      - ./ssh_files/conf/keepalived_server_b.conf:/etc/keepalived/keepalived.conf
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.18
# Contenedores SFTP ip Flotante <<<<<< 192.168.20.23 >>>>>>>
  ssh_emr1:
    container_name: ALMACEN_EMR_1
    hostname: emr1.local
    build:
      context: ./ssh_files
    volumes:
      - ./ssh_emr/key:/root/.ssh
      - ./ssh_emr/conf/sshd_config:/etc/ssh/sshd_config
      - ./ssh_emr/conf/lsyncd.conf.lua:/etc/lsyncd/lsyncd.conf.lua
      - ./ssh_emr/storage_a:/home/remote_user/almacen
      - ./ssh_emr/conf/keepalived_server_a.conf:/etc/keepalived/keepalived.conf
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.21

  ssh_emr2:
    container_name: ALMACEN_EMR_2
    hostname: emr2.local
    build:
      context: ./ssh_files
    volumes:
      - ./ssh_emr/conf/sshd_config:/etc/ssh/sshd_config
      - ./ssh_emr/storage_b:/home/remote_user/almacen
      - ./ssh_emr/key/authorized_keys:/root/.ssh/authorized_keys
      - ./ssh_emr/conf/keepalived_server_b.conf:/etc/keepalived/keepalived.conf
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    networks:
      infra_lab:
        ipv4_address: 192.168.20.22
# Contenedor Jenkins 
  jenkins:
    container_name: JENKINS
    hostname: jenkins.local
    image: jenkins/jenkins:latest
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      infra_lab:
        ipv4_address: 192.168.20.20

networks:
  infra_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1